'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import type { RemoteFile, ClientMessage, ServerMessage } from '@/lib/protocol';

type Pending={resolve:(v:unknown)=>void;reject:(e:Error)=>void};
const join=(a:string,b:string)=>(a==='/'?'':a.replace(/\/+$/,''))+'/'+b;
const parent=(p:string)=>{const a=p.split('/').filter(Boolean);a.pop();return '/'+a.join('/')};
const human=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:n<1073741824?`${(n/1048576).toFixed(1)} MB`:`${(n/1073741824).toFixed(1)} GB`;
const uid=()=>crypto.randomUUID();
const SESSION_KEY='mini-ssh-active-session';
const clearLocalSession=()=>{try{sessionStorage.removeItem(SESSION_KEY)}catch{}};
const b64=(buf:ArrayBuffer)=>{let s='';const u=new Uint8Array(buf);for(let i=0;i<u.length;i+=0x8000)s+=String.fromCharCode(...u.subarray(i,i+0x8000));return btoa(s)};

export default function SSHClient(){
 const [form,setForm]=useState({host:'',port:'22',username:'',password:'',privateKey:'',passphrase:''});
 const [status,setStatus]=useState<'disconnected'|'connecting'|'connected'|'error'>('disconnected');
 const [statusText,setStatusText]=useState('Disconnected'); const [fingerprint,setFingerprint]=useState('');
 const [current,setCurrent]=useState('/'); const [pathInput,setPathInput]=useState('/'); const [files,setFiles]=useState<RemoteFile[]>([]); const [selected,setSelected]=useState<RemoteFile|null>(null); const [busy,setBusy]=useState(''); const [expiresAt,setExpiresAt]=useState(0); const [remaining,setRemaining]=useState('');
 const wsRef=useRef<WebSocket|null>(null); const termRef=useRef<HTMLDivElement>(null); const terminal=useRef<import('@xterm/xterm').Terminal|null>(null); const fit=useRef<import('@xterm/addon-fit').FitAddon|null>(null); const pending=useRef(new Map<string,Pending>()); const downloads=useRef(new Map<string,{name:string;parts:Uint8Array[]}>());
 useEffect(()=>{const tick=()=>{if(!expiresAt){setRemaining('');return;}const left=Math.max(0,expiresAt-Date.now());const mm=Math.floor(left/60000),ss=Math.floor((left%60000)/1000);setRemaining(`${String(mm).padStart(2,'0')}:${String(ss).padStart(2,'0')}`)};tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[expiresAt]);
 useEffect(()=>{const wipe=()=>clearLocalSession();window.addEventListener('pagehide',wipe);return()=>{window.removeEventListener('pagehide',wipe);clearLocalSession()}},[]);
 const send=(m:ClientMessage)=>{const ws=wsRef.current;if(!ws||ws.readyState!==WebSocket.OPEN)throw new Error('WebSocket is not connected');ws.send(JSON.stringify(m));};
 const request=useCallback((m:ClientMessage & {id:string})=>new Promise<unknown>((resolve,reject)=>{pending.current.set(m.id,{resolve,reject});try{send(m)}catch(e){pending.current.delete(m.id);reject(e)}}),[]);
 const load=useCallback(async(p:string)=>{if(wsRef.current?.readyState!==WebSocket.OPEN)return;setBusy('Loading…');setSelected(null);try{const id=uid();const out=await request({type:'list',id,path:p}) as RemoteFile[];out.sort((a,b)=>a.isDirectory===b.isDirectory?a.name.localeCompare(b.name):a.isDirectory?-1:1);setFiles(out);setCurrent(p);setPathInput(p)}catch(e){alert(e instanceof Error?e.message:String(e))}finally{setBusy('')}},[request]);
 useEffect(()=>{let disposed=false;(async()=>{if(!termRef.current)return;const [{Terminal},{FitAddon}]=await Promise.all([import('@xterm/xterm'),import('@xterm/addon-fit')]);if(disposed)return;const t=new Terminal({cursorBlink:true,fontSize:14,fontFamily:'Consolas, "Courier New", monospace',scrollback:5000,theme:{background:'#0b1220',foreground:'#d8e2f0',cursor:'#ffffff'}});const f=new FitAddon();t.loadAddon(f);t.open(termRef.current);f.fit();t.onData(data=>{const ws=wsRef.current;if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:'input',data}))});terminal.current=t;fit.current=f;const ro=new ResizeObserver(()=>{try{f.fit();const ws=wsRef.current;if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:'resize',cols:t.cols,rows:t.rows}))}catch{}});ro.observe(termRef.current);return()=>ro.disconnect()})();return()=>{disposed=true;terminal.current?.dispose();terminal.current=null}},[]);
 const handleMessage=useCallback((m:ServerMessage)=>{if(m.type==='terminal')terminal.current?.write(m.data);else if(m.type==='connected'){setStatus('connected');setStatusText('Connected');setFingerprint(m.fingerprint);setExpiresAt(m.expiresAt);try{sessionStorage.setItem(SESSION_KEY,JSON.stringify({expiresAt:m.expiresAt}))}catch{};setTimeout(()=>load('/'),0);terminal.current?.focus()}else if(m.type==='closed'){setStatus('disconnected');setStatusText(m.reason||'Disconnected');setExpiresAt(0);clearLocalSession();setForm(v=>({...v,password:'',privateKey:'',passphrase:''}));pending.current.forEach(p=>p.reject(new Error(m.reason||'Disconnected')));pending.current.clear();downloads.current.clear()}else if(m.type==='response'){const p=pending.current.get(m.id);if(p){pending.current.delete(m.id);m.ok?p.resolve(m.data):p.reject(new Error(m.error||'Request failed'))}}else if(m.type==='download-start')downloads.current.set(m.id,{name:m.name,parts:[]});else if(m.type==='download-chunk'){const d=downloads.current.get(m.id);if(d){const s=atob(m.data),u=new Uint8Array(s.length);for(let i=0;i<s.length;i++)u[i]=s.charCodeAt(i);d.parts.push(u)}}else if(m.type==='download-end'){const d=downloads.current.get(m.id);if(d){const blob=new Blob(d.parts as BlobPart[]);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=d.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);downloads.current.delete(m.id);setBusy('')}}else if(m.type==='upload-progress')setBusy(`Uploading ${human(m.done)} / ${human(m.total)}`)},[load]);
 const connect=()=>{if(!form.host.trim()||!form.username.trim())return alert('Host và username là bắt buộc.');wsRef.current?.close();setStatus('connecting');setStatusText('Connecting…');setFiles([]);const proto=location.protocol==='https:'?'wss:':'ws:';const ws=new WebSocket(`${proto}//${location.host}/api/ws`);wsRef.current=ws;ws.onopen=()=>{const t=terminal.current;send({type:'connect',host:form.host.trim(),port:Number(form.port)||22,username:form.username.trim(),password:form.password||undefined,privateKey:form.privateKey||undefined,passphrase:form.passphrase||undefined,cols:t?.cols||100,rows:t?.rows||30})};ws.onmessage=e=>{try{handleMessage(JSON.parse(e.data))}catch{}};ws.onerror=()=>{setStatus('error');setStatusText('WebSocket error')};ws.onclose=()=>{setStatus(s=>s==='error'?s:'disconnected');setStatusText(s=>s==='WebSocket error'?s:'Disconnected');setExpiresAt(0);clearLocalSession();setForm(v=>({...v,password:'',privateKey:'',passphrase:''}));pending.current.forEach(p=>p.reject(new Error('Disconnected')));pending.current.clear();downloads.current.clear()}};
 const disconnect=()=>{try{send({type:'disconnect'})}catch{}wsRef.current?.close();wsRef.current=null;setStatus('disconnected');setStatusText('Disconnected');setFiles([]);setFingerprint('');setExpiresAt(0);clearLocalSession();setForm(v=>({...v,password:'',privateKey:'',passphrase:''}));pending.current.forEach(p=>p.reject(new Error('Disconnected')));pending.current.clear();downloads.current.clear()};
 const action=async(m:ClientMessage & {id:string})=>{try{await request(m);await load(current)}catch(e){alert(e instanceof Error?e.message:String(e))}};
 const download=(f:RemoteFile)=>{if(f.isDirectory)return;setBusy(`Downloading ${f.name}…`);send({type:'download',id:uid(),path:join(current,f.name)})};
 const upload=async(file:File)=>{const id=uid(),remote=join(current,file.name);setBusy(`Uploading ${file.name}…`);try{await request({type:'upload-start',id,path:remote,size:file.size});const chunk=256*1024;for(let off=0;off<file.size;off+=chunk){send({type:'upload-chunk',id,data:b64(await file.slice(off,off+chunk).arrayBuffer())});await new Promise(r=>setTimeout(r,0))}await request({type:'upload-end',id});await load(current)}catch(e){alert(e instanceof Error?e.message:String(e))}finally{setBusy('')}};
 return <main className="shell">
  <header><div><h1>Mini SSH Web</h1><p>Next.js 15 · SSH terminal · SFTP</p></div><div className="statusGroup">{status==='connected'&&remaining&&<span className="timer">Session {remaining}</span>}<span className={`badge ${status}`}>{statusText}</span></div></header>
  <section className="connectbar">
   <label>Host<input value={form.host} onChange={e=>setForm({...form,host:e.target.value})} placeholder="server.example.com"/></label><label className="port">Port<input value={form.port} onChange={e=>setForm({...form,port:e.target.value})}/></label><label>User<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>
   <button className="primary" onClick={connect} disabled={status==='connecting'||status==='connected'}>Connect</button><button onClick={disconnect} disabled={status==='disconnected'}>Disconnect</button>
   <details><summary>Private key</summary><textarea value={form.privateKey} onChange={e=>setForm({...form,privateKey:e.target.value})} placeholder="Paste OpenSSH private key (not stored)"/><input type="password" value={form.passphrase} onChange={e=>setForm({...form,passphrase:e.target.value})} placeholder="Passphrase (optional)"/></details>
  </section>
  {fingerprint&&<div className="fingerprint">Host fingerprint: <code>{fingerprint}</code> <strong>⚠ Verify this fingerprint out-of-band before trusting the host.</strong></div>}
  <div className="workspace"><section className="panel terminalPanel"><div className="panelTitle">Terminal <button onClick={()=>terminal.current?.clear()}>Clear</button></div><div ref={termRef} className="terminal"/></section>
   <section className="panel filesPanel"><div className="panelTitle">SFTP <span>{busy}</span></div><div className="toolbar"><button onClick={()=>load(parent(current))}>↑ Up</button><input value={pathInput} onChange={e=>setPathInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load(pathInput||'/')}/><button onClick={()=>load(pathInput||'/')}>Go</button><button onClick={()=>load(current)}>↻</button></div><div className="toolbar"><label className="fileButton">Upload<input type="file" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value=''}}/></label><button onClick={()=>{const n=prompt('Folder name');if(n)action({type:'mkdir',id:uid(),path:join(current,n)})}}>New folder</button><button disabled={!selected||selected.isDirectory} onClick={()=>selected&&download(selected)}>Download</button><button disabled={!selected} onClick={()=>{if(!selected)return;const n=prompt('New name',selected.name);if(n&&n!==selected.name)action({type:'rename',id:uid(),from:join(current,selected.name),to:join(current,n)})}}>Rename</button><button className="danger" disabled={!selected} onClick={()=>{if(selected&&confirm(`Delete ${selected.name}?`))action({type:'delete',id:uid(),path:join(current,selected.name),isDirectory:selected.isDirectory})}}>Delete</button></div>
    <div className="fileHead"><span>Name</span><span>Size</span><span>Modified</span></div><div className="fileList">{files.map(f=><div key={f.name} className={`fileRow ${selected?.name===f.name?'selected':''}`} onClick={()=>setSelected(f)} onDoubleClick={()=>f.isDirectory?load(join(current,f.name)):download(f)}><span>{f.isDirectory?'📁':'📄'} {f.name}</span><span>{f.isDirectory?'':human(f.size)}</span><span>{f.mtime?new Date(f.mtime*1000).toLocaleString():''}</span></div>)}</div>
   </section></div>
  <footer>Session tối đa 60 phút. Không lưu lịch sử, database hoặc persistent cache. Password/private key chỉ ở bộ nhớ của tab; sessionStorage chỉ giữ thời điểm hết hạn và được xóa khi phiên kết thúc.</footer>
 </main>
}
